config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end  

  get 'sessions/new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]

  root 'top#index'
    resources :webpages do
      collection do 
      end
    end
    
    resources :blogs do
      collection do
      post :confirm
      end
    end
end

app/models/blog.rb
class Blog < ApplicationRecord
    
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    belongs_to :user,optional: true
        
    validates :name, presence: true
    validates :title, presence: true
    validates :content, presence: true,
                        length: { minimum: 1, maximum: 140 }
  
    mount_uploader :image, ImageUploader

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    before_action :login_check, only: [:new, :edit, :show ]
 
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
      #変数 = 変数に代入したい値
      #.~で使用するものメソッド
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blogs_params)
    @blog.user_id = current_user.id
    #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    @blog.image.retrieve_from_cache! params[:cache][:image]
    @blog.save!
    if @blog.save
       redirect_to blogs_path, notice: "ブログを作成しました！"
       ContactMailer.contact_mail(@blog).deliver
    else
      render 'new'
    end
  end
  
  def show
    
    # 追記する
    #    @blog = Blog.find(params[:id])
    
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)

  end
  
  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blogs_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  def confirm
    @blog = Blog.new(blogs_params)
  end
 
  
 
  private
  
  def blogs_params
    params.require(:blog).permit(:name, :title, :content, :image, :image_cache, )
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
  def login_check
    if current_user == nil
        redirect_to "/sessions/new"
    end
  end   
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
<center>
  <table border="0">
    <tr>
      <td>
      <div class="blog_title">
        <%= form.label :name %>
      </td>
      <td>
        <%= form.text_field :name %>
      </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="blog_title">
        <%= form.label :title %>
      </td>
      <td>
        <%= form.text_field :title %>
      </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="blog_title">
        <%= form.label :content %>
      </td>
      <td>
        <%= form.text_field :content %>
        </div>
      </td>
    </tr>
     <tr>
       <td>  
          <div class="blog">
          <%= form.label :image %>
        </td>
        <td>
          <%= form.file_field :image, id: :blog_image %>
          <%= form.hidden_field :image_cache %>
          </div>
        </td>
      </tr>
</table>
</center>  
<br>
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>

<center>
        <%= form.hidden_field :name %>
        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>

  <table border="0">
    <tr>
      <td>
         <p>名前:<%= @blog.name %></p>
      </td>
    </tr>
    <tr>
      <td>
        <p>タイトル:<%= @blog.title %></p>
      </td>
    </tr>
    <tr>
      <td>
       <p>本文:<%= @blog.content %></p>
      </td>
    </tr>
    <tr>
      <td>
       <p><%= image_tag(@blog.image_url) %>
      </td>
    </tr>
    <tr>
      <td>
     <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
      </td>
    </tr>
  </table> 
 <br>  
  <%= form.submit  "登録する" %>
<% end %>

<br>
<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
 <%= form.hidden_field :name %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
<br>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
  <h2>ブログを編集する</h2>

  <%= render 'form' %>

app/views/blogs/index.html.erb
<h1>Listing Blogs</h1>

<div class="container">
  <div id="new-blog-link">
    <%= link_to '新規ブログを作成する', new_blog_path %>
  </div>

  <div class="row">
    <% @blogs.each do |blog| %>
      <div class="col-xs-12 col-md-6 blog-panel">
        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= blog.created_at %></p>
        <div class="blog-links">
          <%= link_to 'Show', blog, class: 'btn btn-default' %>
          
          <% if blog.user_id == current_user.id %>
          <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-info' %> |
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div>あなたのメールアドレス：<%= current_user.email %></div>
</div>

app/views/blogs/new.html.erb
<h1>ブログ投稿画面</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細ページ</h1>

<div class="container">
    <div class="row">

<center>        
  <table border="0">
    <tr>
      <th>名前
      </td>
       <td><%= @blog.name %>
        </td>
    </tr>
    <tr>
      <th>タイトル
      </th>
        <td><%= @blog.title %>
        </td>
    </tr>
    <tr>
      <th>内容
      </th>
        <td><%= @blog.content %>
        </td>
    </tr>
    <tr>
      <th>画像
      </th>
        <td><%= image_tag @blog.image %>
        </td>
    </tr>
    </tr>
</table>
</center>

<br>
<% unless @blog.favorite_users == current_user %>
    <% if @favorite.present? %>
        <%= link_to 'お気に入りを解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
        <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-prymary' %>
    <% end %>
<% end %>

<br>

</div>
</div>
<%= link_to 'ブログ一覧画面にもどる |', '/blogs' %>
<%= link_to '新しくブログを投稿する', new_blog_path %>