config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end  

  get 'sessions/new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]

  root 'top#index'
    resources :webpages do
      collection do 
      end
    end
    
    resources :blogs do
      collection do
      post :confirm
      end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <title>EXAMPLE＆Caféページ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
  <header>
 
    <ul>
      <li><%= link_to 'TOP', '/' %></li>
      <li><%= link_to 'LIST', '/webpages' %></li>
      <li><%= link_to 'USER ADD', '/users/new' %></li>
      <li><%= link_to 'LOGIN', '/sessions/new' %></li>
      <li><%= link_to 'BLOG', '/blogs/new' %></li>

    </ul> 

  </header>

  <body>
    <br><br>    <br><br>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

   <% if logged_in? %>
      <%= link_to "Favorite", user_path(current_user.id) %>
       | 
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
  
  
  <footer>
    <p>株式会社EXAMPLE</p>
    <p>2018 01 10.</p>
  </footer>

</html>